# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
A.ndim


2

In [5]:
A.shape

(3, 5)

In [6]:
A.size

15

In [7]:
A.dtype

dtype('int32')

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [8]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [9]:
print (B - C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [10]:
print (B * C)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [11]:
B @ C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix.
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [12]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exponentiate each number elementwise (use the np.exp function).

In [13]:
np.exp(B)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

Calculate the minimum value in the whole matrix.

In [14]:
B.min()

1

Calculcate the minimum value in each row. 


In [15]:
B.min(axis=1)

array([1, 4, 7])

Calculcate the minimum value in each column. 

In [16]:
B.min(axis=0)

array([1, 2, 3])

Find the index value for the minimum value in the whole matrix (hint: use np.argmin).

In [17]:
min_val_index = np.argmin(B)

print(min_val_index)

0


Find the index value for the minimum value in each row (hint: use np.argmin).

In [18]:
min_index_row = np.argmin(B,axis=1)

print(min_index_row)

[0 0 0]


Calculate the sum for all elements.

In [19]:
sum_all_elements = np.sum(B)

sum_all_elements

45

Calculate the mean for each column. 

In [20]:
mean_colum = np.mean(B, axis=0)

mean_colum

array([4., 5., 6.])

Calculate the median for each column.

In [21]:
media_column = np.median(B, axis=0)

media_column

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [22]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [23]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

The missing axes are ignored, i.e., considerd complete slices.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [24]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [26]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [27]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


We are reshaping the array into 2 block and each block will have 3 rows. The -1 tells phyton to count how many colums the new array needs in order to fill the 3 rows.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [28]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [29]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [30]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [31]:
def add_mult_matrices (m1: np.ndarray, m2: np.ndarray, operation: str):
   if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
      print ('Inputs must be numpy.ndarray!')

   if operation == 'add':
      if m1.shape != m2.shape:
         print ('Both matrix must be the same size!') 
      return (m1 + m2)
   
   elif operation == 'multiply':
      if m1.shape[1] != m2.shape[0]:
        print ('Both matrix must be the same size!') 
      return m1 @ m2
         
   else:
       print('Choose either "add" or "multiply"!')
       



In [32]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[1, 2, 3], [8, 4, 3]])

In [33]:
add_mult_matrices(m1, m2, 'add')

array([[ 2,  4,  6],
       [12,  9,  9]])

In [34]:
add_mult_matrices(m1, m2.T, 'multiply')

array([[14, 25],
       [32, 70]])

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [63]:
# 10.1.1

x = np.array([4 ,3])

# a. 1x2
print(x.shape)

# b.
result_a = x * 5
print (result_a)

# c.
result_b = x * 3
print (result_b)

# d.
print(result_a + result_b)

# e. Same answer as c.
print (8 * x)

# f.
print((4*x) - x)

# g.
print(x.T.shape)

# h. Nej men numpy broadcastar
print(x + x.T)

# i.
norm = np.linalg.norm(x)
print('The norm is:', norm)


(2,)
[20 15]
[12  9]
[32 24]
[32 24]
[12  9]
(2,)
[8 6]
The norm is: 5.0


In [36]:
# 10.1.2

# a.
v = np.array([3, 7, 0, 11]).reshape(4, 1)
print (v)

v.shape

[[ 3]
 [ 7]
 [ 0]
 [11]]


(4, 1)

In [37]:
# b.
result_v2 = 2 * v
print(result_v2)

[[ 6]
 [14]
 [ 0]
 [22]]


In [38]:
# c.
result_v5 = v * 5

result_v5 + result_v2

array([[21],
       [49],
       [ 0],
       [77]])

In [39]:
# d.
result_v4 = v * 4

result_v4 - result_v2

array([[ 6],
       [14],
       [ 0],
       [22]])

In [40]:
# f.
normv = np.linalg.norm(v)

print('Norm is:', normv)

Norm is: 13.379088160259652


In [41]:
# 10.1 3

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

print(v1.shape)
print(v2.shape)

(4,)
(4,)


In [42]:
# a.
normv1 = np.linalg.norm(v1)
print(normv1)

7.14142842854285


In [43]:
# b.
resultat_v1v2 = v1 - v2

svar_b =np.linalg.norm(resultat_v1v2)
svar_b

4.47213595499958

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [44]:
# 10.2.1
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([1, 2])
I = np.array([[1, 0], [0, 1]])
    

In [45]:
# a.
res_a = A * 2
res_a

array([[ 4,  2, -2],
       [ 2, -2,  2]])

In [46]:
# b.
B - res_a

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [47]:
#c.
(3 * C) - (2 * E)

array([[ 1,  2],
       [ 4, -1]])

In [48]:
# d.
(2 *D) - (3 * C)

array([[3, 2],
       [2, 3]])

In [49]:
# e.
(D.T) + (2 * D.T)

array([[ 9, 12],
       [12,  9]])

In [50]:
# f.
(2 * C.T) - (2 * D.T)

array([[-4, -4],
       [-4, -4]])

In [51]:
# g.
# (A.T) - (B) Ej definierat

In [52]:
# h.
# A * C Ej definierat

In [53]:
# i.
C @ D

array([[11, 10],
       [10, 11]])

In [54]:
# j.
C @ B

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

In [55]:
# k.
C @ I

array([[1, 2],
       [2, 1]])

In [56]:
# l.
A @ B.T

array([[5, 2],
       [7, 4]])

In [57]:
# 10.2.2
A1 = np.array([[2, 3, 4], [5, 4, 1]])

print (A1.shape)

print(A1 @ A1.T)

(2, 3)
[[29 26]
 [26 42]]


In [58]:
# 10.2.3
A2 = np.array([[1 ,2], [2 , 4]])
B2 = np.array([[2, 1], [1, 3]])
C2 = np.array([[4 ,3], [0, 2]])

print(A2.shape)
print(B2.shape)
print(C2.shape)

print(A2 @ B2)
print(A2 @ C2)

(2, 2)
(2, 2)
(2, 2)
[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [59]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [60]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [61]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
